"""initial

Revision ID: f1b28a5e47a5
Revises: 
Create Date: 2025-11-21 23:56:01.884979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1b28a5e47a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

# def upgrade() -> None:
#     """
#     يضيف خيارات جديدة إلى نوع التعداد 'appstatus' في PostgreSQL.
#     """
#     # ⚠️ يجب التأكد من أن اسم التعداد في قاعدة البيانات هو 'appstatus'
    
#     # 1. تعريف القيم الجديدة والقديمة
#     new_status_values = ["Active", "Pause", "Cancel"]
    
#     try:
#         # إضافة 'Pause' (إذا كانت جديدة)
#         op.execute("ALTER TYPE appstatus ADD VALUE 'Pause'") 
#     except:
#         # تجاوز الخطأ إذا كانت القيمة موجودة بالفعل (لتجنب فشل الترحيل)
#         pass 
        
#     try:
#         # إضافة 'Cancel' (إذا كانت جديدة)
#         op.execute("ALTER TYPE appstatus ADD VALUE 'Cancel'")
#     except:
#         pass

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
